"""
ORBITAL SHIELD — ML Correlation Brain
Step 3: Rule-based correlation engine

Rules are loaded from config/rules.yaml — NOT hardcoded here.
Each rule is evaluated independently on every newly ingested event.
When a rule fires, an incident is generated by the scoring engine.

Design principle: every decision is deterministic, explainable, and auditable.
"""

import logging
import yaml
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger("orbital.correlation")

_SEVERITY_ORDER = {"LOW": 0, "MEDIUM": 1, "HIGH": 2, "CRITICAL": 3}
_CONFIG_PATH = Path(__file__).parent.parent / "config" / "rules.yaml"


# ─────────────────────────────────────────────────────────────
# Config loader (hot-reloadable)
# ─────────────────────────────────────────────────────────────

def load_config() -> dict:
    """Load and return the full rules.yaml config. Called on each evaluation so
    config changes take effect without a restart."""
    with open(_CONFIG_PATH, "r") as f:
        return yaml.safe_load(f)


def get_rules() -> list[dict]:
    return load_config().get("rules", [])


def get_scoring_config() -> dict:
    return load_config().get("scoring", {})


def get_window_config() -> dict:
    return load_config().get("window", {})


def get_feedback_config() -> dict:
    return load_config().get("feedback", {})


# ─────────────────────────────────────────────────────────────
# Main correlation entry point
# ─────────────────────────────────────────────────────────────

def evaluate_rules(new_event: dict, window_events: list[dict]) -> list[dict]:
    """
    Evaluate all enabled rules against the new event and the current
    sliding window. Returns a list of 'fired rule' dicts — one per
    rule that matched. Each dict contains everything the scoring engine
    needs to build a full CorrelationIncident.

    Args:
        new_event:     The freshly ingested event (already in the window).
        window_events: All events currently in the sliding window.

    Returns:
        List of matched-rule dicts (empty list if no rules fire).
    """
    rules = get_rules()
    results = []

    for rule in rules:
        if not rule.get("enabled", True):
            continue
        try:
            match = _evaluate_single_rule(rule, new_event, window_events)
            if match:
                results.append(match)
                logger.info(
                    "Rule FIRED: %s (%s) | satellite=%s | matched_events=%d",
                    rule["id"], rule["name"],
                    new_event["satellite_id"],
                    len(match["matched_events"])
                )
        except Exception as exc:
            logger.error("Error evaluating rule %s: %s", rule.get("id"), exc, exc_info=True)

    return results


# ─────────────────────────────────────────────────────────────
# Individual rule evaluators
# ─────────────────────────────────────────────────────────────

def _evaluate_single_rule(rule: dict, new_event: dict, window_events: list[dict]) -> dict | None:
    """
    Returns a match dict if the rule fires, else None.
    Dispatches to sub-evaluators based on rule conditions.
    """
    conditions = rule.get("conditions", {})
    match_key      = conditions.get("match_key", "satellite_id")
    time_window    = conditions.get("time_window_seconds", 300)
    min_sources    = conditions.get("min_sources", 2)
    min_events     = conditions.get("min_events", 2)
    required_srcs  = conditions.get("required_sources", [])
    severity_pat   = conditions.get("severity_pattern")
    min_severity   = conditions.get("min_severity")
    min_confidence = conditions.get("min_confidence", 0.0)

    # ── Step 1: Build the candidate event pool ─────────────────
    join_value = new_event.get(match_key)
    if not join_value:
        return None  # can't correlate without the join key

    candidates = _filter_by_key_and_window(
        window_events, match_key, join_value, time_window
    )

    # ── Step 2: Apply optional severity / confidence filters ───
    if min_severity:
        min_ord = _SEVERITY_ORDER.get(min_severity, 0)
        candidates = [e for e in candidates
                      if _SEVERITY_ORDER.get(e["severity"], 0) >= min_ord]
    if min_confidence > 0.0:
        candidates = [e for e in candidates if e["confidence"] >= min_confidence]

    if len(candidates) < min_events:
        return None

    # ── Step 3: Distinct sources check ────────────────────────
    sources_present = set(e["source"] for e in candidates)
    if len(sources_present) < min_sources:
        return None

    # ── Step 4: Required sources check ────────────────────────
    for req in required_srcs:
        if req not in sources_present:
            return None

    # ── Step 5: Severity escalation pattern (Rule 002 style) ──
    if severity_pat:
        if not _check_severity_pattern(candidates, severity_pat):
            return None

    # ── Rule fired — build the match result ───────────────────
    return _build_match(rule, candidates, new_event, match_key, join_value)


def _filter_by_key_and_window(events: list[dict], key: str, value: str,
                               window_seconds: int) -> list[dict]:
    """Return events that match `key=value` and fall within `window_seconds` of the most recent."""
    matching = [e for e in events if e.get(key) == value]
    if not matching:
        return []

    # Use the timestamp of the most-recent matching event as the reference point
    latest_ts = max(_parse_ts(e["timestamp"]) for e in matching)
    cutoff = latest_ts.timestamp() - window_seconds

    return [
        e for e in matching
        if _parse_ts(e["timestamp"]).timestamp() >= cutoff
    ]


def _check_severity_pattern(events: list[dict], pattern: list[str]) -> bool:
    """
    Check whether events contain at least one occurrence of each severity level
    in `pattern`, and that they appear in ascending order (by timestamp).
    """
    sorted_events = sorted(events, key=lambda e: _parse_ts(e["timestamp"]))
    severities = [e["severity"] for e in sorted_events]

    pattern_idx = 0
    for sev in severities:
        if pattern_idx >= len(pattern):
            break
        if sev == pattern[pattern_idx]:
            pattern_idx += 1

    return pattern_idx >= len(pattern)


def _build_match(rule: dict, candidates: list[dict], trigger_event: dict,
                 match_key: str, join_value: str) -> dict:
    """Assemble the match result dict passed to the scoring engine."""
    sources = sorted(set(e["source"] for e in candidates))
    event_types = sorted(set(e["event_type"] for e in candidates))
    severities = sorted(set(e["severity"] for e in candidates),
                        key=lambda s: _SEVERITY_ORDER[s])

    # Build human-readable description explaining WHY the rule fired
    description = _build_description(rule, candidates, sources, event_types,
                                     match_key, join_value)

    return {
        "rule_id":       rule["id"],
        "rule_name":     rule["name"],
        "incident_type": rule["incident_type"],
        "matched_events": candidates,
        "trigger_event": trigger_event,
        "sources":       sources,
        "event_types":   event_types,
        "severities":    severities,
        "match_key":     match_key,
        "join_value":    join_value,
        "description":   description,
        "satellite_id":  trigger_event.get("satellite_id"),
        "operator_id":   trigger_event.get("operator_id"),
        "session_id":    trigger_event.get("session_id"),
    }


def _build_description(rule: dict, candidates: list[dict], sources: list[str],
                        event_types: list[str], match_key: str, join_value: str) -> str:
    """
    Build a descriptive, human-readable explanation of why the rule fired.
    This is shown verbatim to the CISO — it must be specific, not generic.
    """
    times = sorted(_parse_ts(e["timestamp"]) for e in candidates)
    if len(times) >= 2:
        span_seconds = int((times[-1] - times[0]).total_seconds())
        span_str = f"{span_seconds // 60}m {span_seconds % 60}s" if span_seconds >= 60 else f"{span_seconds}s"
    else:
        span_str = "0s"

    source_str  = " + ".join(sources)
    type_str    = ", ".join(event_types)
    sat_id      = candidates[0].get("satellite_id", "UNKNOWN")
    event_ids   = [e["event_id"] for e in candidates]

    # Rule-specific narrative
    if rule["id"] == "RULE_001":
        return (
            f"[{rule['name']}] Session {join_value} generated events from {len(sources)} independent "
            f"security modules ({source_str}) within {span_str}: event types [{type_str}]. "
            f"Cross-module activity on a single session is a strong indicator of a compromised "
            f"session or coordinated attack. Contributing events: {event_ids}."
        )
    elif rule["id"] == "RULE_002":
        sev_seq = " → ".join(e["severity"] for e in sorted(candidates, key=lambda e: _parse_ts(e["timestamp"])))
        return (
            f"[{rule['name']}] Satellite {sat_id} shows an escalating severity chain "
            f"({sev_seq}) across {len(candidates)} events spanning {span_str} from modules [{source_str}]. "
            f"Progressive severity escalation suggests a developing or multi-stage attack. "
            f"Contributing events: {event_ids}."
        )
    elif rule["id"] == "RULE_003":
        return (
            f"[{rule['name']}] Satellite {sat_id} received a FIRMWARE integrity event and an ACCESS "
            f"anomaly event within {span_str} — a known supply-chain attack pattern where malicious "
            f"firmware is combined with compromised credentials. Sources: [{source_str}]. "
            f"Contributing events: {event_ids}."
        )
    elif rule["id"] == "RULE_004":
        return (
            f"[{rule['name']}] Satellite {sat_id} is under simultaneous observation from "
            f"{len(sources)} independent security modules ({source_str}) within {span_str}. "
            f"Event types: [{type_str}]. Multi-vector simultaneous activity strongly suggests "
            f"a coordinated attack. Contributing events: {event_ids}."
        )
    elif rule["id"] == "RULE_005":
        avg_conf = sum(e["confidence"] for e in candidates) / len(candidates)
        return (
            f"[{rule['name']}] {len(candidates)} high-confidence events (avg confidence {avg_conf:.2f}) "
            f"of severity HIGH/CRITICAL from modules [{source_str}] targeted {sat_id} within {span_str}. "
            f"High-fidelity multi-module signals: [{type_str}]. Immediate review required. "
            f"Contributing events: {event_ids}."
        )
    else:
        # Generic fallback for custom rules added to the config
        return (
            f"[{rule['name']}] Rule '{rule['id']}' fired on {match_key}={join_value}. "
            f"{len(candidates)} events from modules [{source_str}] within {span_str}. "
            f"Event types: [{type_str}]. Contributing events: {event_ids}."
        )


# ─────────────────────────────────────────────────────────────
# Deduplication guard
# ─────────────────────────────────────────────────────────────

def is_duplicate_incident(rule_id: str, matched_event_ids: list[str],
                           existing_incidents: list[dict]) -> bool:
    """
    Prevent re-firing the same rule on the exact same set of events.
    An incident is considered a duplicate if the same rule already produced
    an OPEN incident covering all the same event IDs.
    """
    matched_set = set(matched_event_ids)
    for inc in existing_incidents:
        if inc.get("rule_id") == rule_id and inc.get("status") == "OPEN":
            existing_set = set(inc.get("related_events", []))
            # Overlap of 80% or more → treat as duplicate
            if len(matched_set & existing_set) / max(len(matched_set), 1) >= 0.8:
                return True
    return False


# ─────────────────────────────────────────────────────────────
# Utility
# ─────────────────────────────────────────────────────────────

def _parse_ts(ts) -> datetime:
    if isinstance(ts, datetime):
        return ts.replace(tzinfo=timezone.utc) if ts.tzinfo is None else ts
    try:
        dt = datetime.fromisoformat(str(ts).replace("Z", "+00:00"))
        return dt.replace(tzinfo=timezone.utc) if dt.tzinfo is None else dt
    except ValueError:
        return datetime.now(timezone.utc)
